name: libarweave
description: A simple library for interacting with the Arweave blockchain
# version: 0.0.1
# homepage: https://www.github.com/acolytec3/libarweave

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  jose: '>=0.1.2'
  crypto: '>=2.1.3'
  http: '>=0.0.0'

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
